import catalog from '@/config/domain-tools.json';
import { objectBody, RequestError } from './record-policy';
function text(v:unknown,label:string):string {if(typeof v!=='string'||!v.trim())throw new RequestError(`${label} is required`);return v.trim();}
function n(v:unknown,label:string,min=0,max=1e12):number {if((typeof v!=='number'&&typeof v!=='string')||String(v).trim()==='')throw new RequestError(`${label} must be numeric`);const x=Number(v);if(!Number.isFinite(x)||x<min||x>max)throw new RequestError(`${label} is outside its allowed range`);return x;}
function integer(v:unknown,label:string){const x=n(v,label);if(!Number.isSafeInteger(x))throw new RequestError(`${label} must be integer minor units or whole counts`);return x;}
function rows(v:unknown,label:string){if(!Array.isArray(v)||!v.length||v.length>10000)throw new RequestError(`${label} requires 1–10,000 rows`);return v.map(objectBody);}
function unique(items:Record<string,unknown>[]){const seen=new Set<string>();for(const row of items){const id=text(row.id,'Record identifier');if(seen.has(id))throw new RequestError(`Duplicate identifier: ${id}`);seen.add(id);}return items;}
function date(v:unknown){const s=text(v,'ISO timestamp');const t=new Date(s);if(!/^\d{4}-\d{2}-\d{2}(T.*)?$/.test(s)||!Number.isFinite(t.getTime())||t.toISOString().slice(0,10)!==s.slice(0,10))throw new RequestError('Use a valid ISO date or timestamp');return t.getTime();}
function sum(values:number[]){const x=values.reduce((a,b)=>a+b,0);if(!Number.isFinite(x)||Math.abs(x)>Number.MAX_SAFE_INTEGER)throw new RequestError('Calculation exceeds safe numeric precision');return x;}
function round(x:number){if(!Number.isFinite(x))throw new RequestError('Non-finite calculation');return Math.round(x*1e6)/1e6;}
function money(x:bigint,divisor=1n){const value=Number((x+divisor/2n)/divisor);if(!Number.isSafeInteger(value))throw new RequestError('Calculation exceeds safe numeric precision');return value;}
function boolean(v:unknown){if(typeof v!=='boolean')throw new RequestError('Expected true or false');return v;}
function tags(v:unknown){if(!Array.isArray(v)||!v.every(x=>typeof x==='string'&&x.trim()))throw new RequestError('Expected nonempty text tags');return [...new Set(v.map(x=>String(x).trim().toLowerCase()))];}
export function calculate(operation:string,input:unknown):Record<string,unknown>{
 const d=objectBody(input);if(['payroll','coverage','progress','windows','emissions','effluent','thresholds','dose','consent','credits','jurypay','offsets'].includes(operation)||'ruleSource'in d)text(d.ruleSource,'Reviewed rule source/version');
 switch(operation){
 case 'payroll':{const regular=integer(d.regularMinutes,'Regular minutes'),overtime=integer(d.overtimeMinutes,'Overtime minutes'),base=integer(d.baseRateCents,'Base cents'),fringe=integer(d.fringeRateCents,'Fringe cents'),mult=n(d.overtimeMultiplier,'Overtime multiplier',1,10);if(!Number.isInteger(mult*1000))throw new RequestError('Overtime multiplier supports three decimals');const wages=money(BigInt(regular)*BigInt(base)*1000n+BigInt(overtime)*BigInt(base)*BigInt(Math.round(mult*1000)),60000n);const fringes=money(BigInt(regular+overtime)*BigInt(fringe),60n);return{requiredWageCents:wages,requiredFringeCents:fringes,wageShortfallCents:Math.max(0,wages-integer(d.grossPaidCents,'Gross paid cents')),fringeShortfallCents:Math.max(0,fringes-integer(d.fringePaidCents,'Fringe paid cents')),method:'Separate wage and fringe obligations; overtime multiplier applies only to base wages; half-up cent rounding'};}
 case 'coverage':{const outstanding=Math.max(0,integer(d.invoiceCents,'Invoice')-integer(d.paymentsCents,'Payments')),limit=integer(d.buyerLimitCents,'Limit'),deductible=integer(d.deductibleCents,'Deductible'),percent=n(d.coveragePercent,'Coverage percent',0,100);return{outstandingCents:outstanding,uninsuredLimitExcessCents:Math.max(0,outstanding-limit),scenarioRecoveryCents:Math.round(Math.max(0,Math.min(outstanding,limit)-deductible)*percent/100),method:'Deductible applied before entered coverage percent; validate policy wording'};}
 case 'inventory':{const expected=n(d.opening,'Opening')+n(d.received,'Received')-n(d.issued,'Issued');const variance=n(d.measuredClosing,'Closing')-expected;return{unit:text(d.unit,'Unit'),expectedClosing:round(expected),variance:round(variance),withinTolerance:Math.abs(variance)<=n(d.tolerance,'Tolerance'),negativeExpectedBalance:expected<0};}
 case 'progress':{const checks=unique(rows(d.requirements,'Requirements')).map(r=>{const required=n(r.required,'Required',Number.MIN_VALUE),completed=n(r.completed,'Completed');return{id:r.id,required,completed,remaining:round(Math.max(0,required-completed)),percent:round(Math.min(100,completed/required*100))};});return{checks,allRecordedRequirementsMet:checks.every(c=>c.remaining===0),scope:'Quantitative coverage only; evidence adequacy and authorization require review'};}
 case 'windows':{const event=date(d.eventAt);return{eventAt:new Date(event).toISOString(),checks:unique(rows(d.documents,'Validity windows')).map(r=>{const from=date(r.validFrom),until=date(r.validUntil);if(until<from)throw new RequestError('Validity end precedes start');return{id:r.id,coversEvent:from<=event&&event<=until,hoursUntilExpiry:round((until-event)/3600000)}})};}
 case 'emissions':{const uncontrolled=n(d.activityUnits,'Activity')*n(d.factorKgPerUnit,'Factor'),controlled=uncontrolled*(1-n(d.controlEfficiencyPercent,'Efficiency',0,100)/100),limit=n(d.limitKg,'Limit');return{uncontrolledKg:round(uncontrolled),controlledKg:round(controlled),excessKg:round(Math.max(0,controlled-limit)),withinEnteredLimit:controlled<=limit};}
 case 'effluent':{const concentration=n(d.concentrationMgL,'Concentration'),load=concentration*n(d.flowM3,'Flow')/1000;return{loadKg:round(load),withinConcentrationLimit:concentration<=n(d.concentrationLimitMgL,'Concentration limit'),withinLoadLimit:load<=n(d.loadLimitKg,'Load limit'),conversion:'1 mg/L × 1 m³ = 0.001 kg'};}
 case 'ledger':{const additions=unique(rows(d.additions,'Additions')),deductions=unique(rows(d.deductions,'Deductions'));unique([...additions,...deductions]);const incoming=sum(additions.map(r=>n(r.amount,'Addition'))),outgoing=sum(deductions.map(r=>n(r.amount,'Deduction'))),balance=sum([n(d.opening,'Opening'),incoming,-outgoing]);return{unit:text(d.unit,'Unit'),additions:incoming,deductions:outgoing,balance:round(balance),overage:round(Math.max(0,-balance))};}
 case 'thresholds':return{checks:unique(rows(d.readings,'Readings')).map(r=>{const lower=n(r.lower,'Lower',-1e12),upper=n(r.upper,'Upper',lower),value=n(r.value,'Reading',-1e12);return{id:r.id,unit:text(r.unit,'Unit'),value,lower,upper,withinEnteredBounds:lower<=value&&value<=upper}})};
 case 'budget':{const items=unique(rows(d.items,'Commitments'));const committed=sum(items.map(r=>integer(r.committedCents,'Commitment'))),paid=sum(items.map(r=>integer(r.paidCents,'Paid'))),budget=integer(d.budgetCents,'Budget');return{currency:text(d.currency,'Currency'),committedCents:committed,paidCents:paid,unpaidCommitmentsCents:committed-paid,uncommittedBudgetCents:budget-committed,overpayments:items.filter(r=>Number(r.paidCents)>Number(r.committedCents)).map(r=>r.id)};}
 case 'dose':{const total=sum(unique(rows(d.readings,'Measurements')).map(r=>n(r.value,'Dose')));return{doseType:text(d.doseType,'Dose type'),unit:text(d.unit,'Unit'),total:round(total),aboveEnteredReviewThreshold:total>n(d.threshold,'Threshold'),assumptions:'Same dose type and units; non-overlapping measurement periods; values are not clinical recommendations'};}
 case 'trace':{const target=text(d.target,'Target'),links=rows(d.links,'Trace links'),seen=new Set([target]),queue=[target];for(const row of links){text(row.from,'From');text(row.to,'To');}while(queue.length){const current=queue.shift();for(const row of links)if(row.from===current&&!seen.has(String(row.to))){seen.add(String(row.to));queue.push(String(row.to));}}return{target,downstream:[...seen].filter(x=>x!==target),scope:'Reachability in supplied relationships; no notifications sent'};}
 case 'consent':{const allowed=tags(d.allowedUses),prohibited=tags(d.prohibitedUses),requested=tags(d.requestedUses),withdrawn=boolean(d.withdrawn);return{withdrawn,prohibitedMatches:requested.filter(x=>prohibited.includes(x)),unmatchedUses:requested.filter(x=>!allowed.includes(x)),reviewRequired:true,scope:'Tag matching only; no automatic specimen access'};}
 case 'timeline':{const deadline=date(d.deadlineAt),legs=unique(rows(d.legs,'Transport legs'));let prior:number|undefined;const conflicts:string[]=[];const result=legs.map(r=>{const start=date(r.departAt),end=date(r.arriveAt);if(end<start)throw new RequestError('Arrival precedes departure');if(prior!==undefined&&start<prior)conflicts.push(String(r.id));const wait=prior===undefined?null:round((start-prior)/60000);prior=end;return{id:r.id,travelMinutes:round((end-start)/60000),connectionMinutes:wait};});return{legs:result,overlappingLegs:conflicts,arrivalBufferMinutes:round((deadline-prior!)/60000),arrivesByDeadline:prior!<=deadline};}
 case 'custody':{let holder=text(d.initialCustodian,'Initial custodian'),prior=-Infinity;const exceptions:unknown[]=[];for(const r of unique(rows(d.transfers,'Transfers'))){const at=date(r.at),from=text(r.from,'From'),to=text(r.to,'To'),seal=boolean(r.sealIntact);if(from!==holder||at<prior||!seal)exceptions.push({id:r.id,custodianMismatch:from!==holder,outOfOrder:at<prior,sealException:!seal});holder=to;prior=at;}return{finalRecordedCustodian:holder,exceptions,continuousUnderInputs:exceptions.length===0};}
 case 'credits':{const courses=unique(rows(d.courses,'Courses'));const awards=sum(courses.map(r=>n(r.awardedCredits,'Awarded credits'))),source=sum(courses.map(r=>n(r.sourceCredits,'Source credits')));return{sourceCredits:source,awardedCredits:awards,capExcess:round(Math.max(0,awards-n(d.maximumCredits,'Maximum'))),awardsExceedingSource:courses.filter(r=>Number(r.awardedCredits)>Number(r.sourceCredits)).map(r=>r.id)};}
 case 'deadlines':{const now=date(d.asOf);return{asOf:new Date(now).toISOString(),items:unique(rows(d.items,'Deadline items')).map(r=>{const remaining=(date(r.dueAt)-now)/86400000,completed=boolean(r.completed);return{id:r.id,daysRemaining:round(remaining),completed,overdue:!completed&&remaining<0}})};}
 case 'jurypay':{const service=money(BigInt(integer(d.serviceDays,'Service days'))*BigInt(integer(d.dailyCents,'Daily cents'))),miles=n(d.travelMiles,'Miles');if(!Number.isInteger(miles*1000))throw new RequestError('Mileage supports three decimals');const travel=money(BigInt(Math.round(miles*1000))*BigInt(integer(d.mileageCents,'Mileage cents')),1000n),gross=sum([service,travel]);return{serviceCents:service,travelCents:travel,totalCents:gross,outstandingCents:Math.max(0,gross-integer(d.priorPaidCents,'Prior payments'))};}
 case 'offsets':{const claim=integer(d.claimCents,'Claim'),allowed=integer(d.allowedCents,'Allowed');if(allowed>claim)throw new RequestError('Allowed expenses exceed submitted claim');return{netExpenseCents:Math.max(0,allowed-integer(d.otherPayerCents,'Offsets')),scenarioAwardCents:Math.min(integer(d.programCapCents,'Cap'),Math.max(0,allowed-Number(d.otherPayerCents))),eligibilityDetermined:false};}
 case 'compare':{const left=unique(rows(d.left,'Original inventory')),right=unique(rows(d.right,'Updated inventory'));for(const r of [...left,...right])text(r.value,'Inventory value');const a=new Map(left.map(r=>[String(r.id),r.value])),b=new Map(right.map(r=>[String(r.id),r.value]));return{missing:left.filter(r=>!b.has(String(r.id))),added:right.filter(r=>!a.has(String(r.id))),changed:right.filter(r=>a.has(String(r.id))&&a.get(String(r.id))!==r.value).map(r=>({id:r.id,before:a.get(String(r.id)),after:r.value}))};}
 case 'numbers':{if(!Array.isArray(d.numbers)||!d.numbers.length||!d.numbers.every(x=>typeof x==='string'))throw new RequestError('Supply telephone number strings');const seen=new Set(),duplicates=new Set();const invalid:string[]=[];for(const raw of d.numbers){const v=raw.trim();if(!/^\+[1-9]\d{7,14}$/.test(v))invalid.push(v);if(seen.has(v))duplicates.add(v);seen.add(v);}return{uniqueCount:seen.size,duplicates:[...duplicates],invalid,scope:'Syntax and duplicates only; carrier acceptance and ownership not verified'};}
 case 'evidence':return{checks:unique(rows(d.requirements,'Evidence requirements')).map(r=>({id:r.id,requirement:text(r.requirement,'Requirement'),present:typeof r.evidence==='string'&&r.evidence.trim().length>0})),scope:'Presence only; review source quality and applicable requirements'};
 default:throw new RequestError('Unknown calculation',404);
 }
}
export function runTool(id:string,input:unknown){const tool=catalog.find(x=>x.id===id);if(!tool)throw new RequestError('Unknown domain tool',404);return{...calculate(tool.operation,input),methodVersion:'1.0',ruleSource:objectBody(input).ruleSource??null};}
